#!/usr/bin/env perl

# check-option-types checks standard option types (s, i, etc.) and short forms.
# http://code.google.com/p/maatkit/issues/detail?id=1177

BEGIN {
   die "The MAATKIT_WORKING_COPY environment variable is not set.  See http://code.google.com/p/maatkit/wiki/Testing"
      unless $ENV{MAATKIT_WORKING_COPY} && -d $ENV{MAATKIT_WORKING_COPY};
   unshift @INC, "$ENV{MAATKIT_WORKING_COPY}/common";
};

use strict;
use warnings FATAL => 'all';

use Cwd;
use English qw(-no_match_vars);
use Data::Dumper;

use MaatkitTest;

# This programs are assumed to be in PATH.
my $pod2text = 'pod2text';
my $aspell   = 'aspell';

my @progs = @ARGV;
if ( !@progs ) {
   my $cwd = cwd();
   chdir $trunk;
   @progs = <./mk-*/mk-*>;
   chdir $cwd;
}

my %dir_for_tool = (
   'mk-checksum-filter'   => 'mk-table-checksum',
   'mk-merge-mqd-results' => 'mk-query-digest',
   'mk-profile-compact'   => 'mk-query-profiler',
);

foreach my $prog ( @progs ) {
   my ($tool) = $prog =~ m{([a-z-]+)$};
   next unless $tool;
   my $dir = "$trunk/" . ($dir_for_tool{$tool} || $tool) . '/';

   `$pod2text $dir/$tool > /tmp/$tool-pod.txt`;

   `cat /tmp/$tool-pod.txt | $aspell --pipe --lang en_US --personal $trunk/maatkit/spell-check/aspell.en.pws > /tmp/$tool-misspelled-words.txt`;

   print "$tool:\n\n";
   print `$trunk/maatkit/spell-check/parse_ispell_output /tmp/$tool-misspelled-words.txt /tmp/$tool-pod.txt`;
   print "\n";

   `rm -rf /tmp/$tool-pod.txt`;
   `rm -rf /tmp/$tool-misspelled-words.txt`;
}

exit;
